services:
    overleaf:
        restart: always
        build: images/overleaf
        container_name: overleaf
        depends_on:
            overleaf_mongo:
                condition: service_healthy
            overleaf_redis:
                condition: service_started
        ports:
            - 8085:80
        links:
            - overleaf_mongo
            - overleaf_redis
        stop_grace_period: 60s
        volumes:
            - ./volumes/data:/var/lib/overleaf
        environment:
            ENABLE_CONVERSIONS: 'true'
            EMAIL_CONFIRMATION_DISABLED: 'true'
            REDIS_HOST: overleaf_redis
            GIT_BRIDGE_ENABLED: 'false'
            OVERLEAF_APP_NAME: Overleaf Community Edition
            GIT_BRIDGE_HOST: 'git-bridge'
            OVERLEAF_REDIS_HOST: overleaf_redis
            V1_HISTORY_URL: http://overleaf:3100/api
            EXTERNAL_AUTH: none
            GIT_BRIDGE_PORT: 8000
            OVERLEAF_MONGO_URL: mongodb://overleaf_mongo/overleaf
            REDIS_PORT: 6379
            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

    overleaf_mongo:
        restart: always
        build: images/mongo
        container_name: overleaf_mongo
        command: "--replSet overleaf"
        expose:
            - 27017
        volumes:
            - ./volumes/mongo/data:/data/db
            - ./volumes/mongo/config:/data/configdb
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
        environment:
            MONGODB_REPLICA_SET_MODE: primary
            ALLOW_EMPTY_PASSWORD: 'yes'

    overleaf_redis:
        restart: always
        image: redis:6.2
        container_name: overleaf_redis
        expose:
            - 6379
        volumes:
            - ./volumes/redis/data:/data